plugin:
  backend: go-plugin
  go-plugin:
    dir: ../../../scheme/bin/
ta-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: ta-store.sql
en-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: en-store.sql
po-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: po-store.sql
po-agent:
  backend: opa
vts:
  server-addr: localhost:50051
ear-signer:
  alg: ES256
  key: ./skey.jwk
logging:
  level: debug
