# This config file is assumes the services is being run via "debug" command
# from the docker deployment debug shell.
logging:
  level: debug  # valid levels: error, warning, info, debug
provisioning:
  listen-addr: 0.0.0.0:8888
vts:
  server-addr: localhost:50051
# vim: set ft=yaml:
