# This config file is assumes the services is being run via "debug" command
# from the docker deployment debug shell.
logging:
  level: debug  # valid levels: error, warning, info, debug
provisioning:
  listen-addr: 0.0.0.0:8888
vts:
  server-addr: vsock://5:50051
#  server-addr: vts-service:50051
plugin:
  backend: builtin

# vim: set ft=yaml:
